name: Delete Packages Cache

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:

  delete_linux_packages_cache:
    name: Delete Linux Packages Cache
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: Delete Packages Cache
      run: |
        gh cache delete pkg-linux-${{ github.event.workflow_run.head_sha }}-${{ github.event.workflow_run.id }}
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}

  delete_macos_packages_cache:
    name: Delete macOS Packages Cache
    runs-on: macos-14
    permissions:
      actions: write
    steps:
    - name: Delete Packages Cache
      run: |
        gh cache delete pkg-macos-${{ github.event.workflow_run.head_sha }}-${{ github.event.workflow_run.id }}
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
